### ISSUE TITLE
Write after end

### ISSUE THREAD

**Issue by jasbrake** [jasbrake/actionfps-log-stream#7]
```
2017-09-27 02:27 +00:00: Error: write after end
    at writeAfterEnd (_stream_writable.js:234:12)
    at WriteStream.Writable.write (_stream_writable.js:285:5)
    at EventSource.eventSource.addEventListener (/usr/lib/node_modules/actionfps-log-stream/actionfps-log-stream.js:48:17)
    at emitOne (events.js:115:13)
    at EventSource.emit (events.js:210:7)
    at _emit (/usr/lib/node_modules/actionfps-log-stream/node_modules/eventsource/lib/eventsource.js:222:17)
    at parseEventStreamLine (/usr/lib/node_modules/actionfps-log-stream/node_modules/eventsource/lib/eventsource.js:237:9)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/actionfps-log-stream/node_modules/eventsource/lib/eventsource.js:200:11)
    at emitOne (events.js:115:13)
    at IncomingMessage.emit (events.js:210:7)
```

I think the issue is that I am ending the writeStream on an error event from the eventsource server.

**Comment by jasbrake** [comment]
Closed unless the issue is seen again in the server logs.

**Comment by ScalaWilliam** [comment]
You may consider upgrading EventSource dependency btw.

**Comment by jasbrake** [comment]
Hm yes, I'm still using 1.0.0 when 1.0.5 is the current version. Thanks @ScalaWilliam.
